### ISSUE TITLE
Web Side Errors for repeat and shuffle with stations on Amazon Music

### ISSUE THREAD

**Issue by ceylon23** [tjhrulz/WebNowPlaying-BrowserExtension#14]
When listening to a "Station" on Amazon Prime there is no "Shuffle" or "Repeat" available. This makes Rainmeter throw both a "Web Side Error:Error updating shuffle for Amazon Music" error and a "Web Side Error:Error updating repeat for Amazon Music" error every 100ms. However, when listening to an album or other playlist where "Shuffle" and "Repeat" are available, these errors do not occur.

**Comment by tjhrulz** [comment]
Good catch, I had forgotten that Amazon had a radio mode. I am busy the next few days but will try to get to it over the weekend.

**Comment by ceylon23** [comment]
Sorry to be a nuisance on this one but I updated the file and loaded the unpacked extension and it seems to still be catching the same error. I also refreshed the rainmeter skins and restarted rainmeter.  For testing purposes I did the whole sequence of download and load of unpacked extension and the error is repeatable. See attachment.
![image](https://user-images.githubusercontent.com/3222728/35319439-b29a167e-0101-11e8-99c6-596b8254f65a.png)

**Comment by tjhrulz** [comment]
Did you disable the existing plug-in?

**Comment by ceylon23** [comment]
Yes, I even removed the original extension and made sure it was removed
from within the extensions folder.

**Comment by tjhrulz** [comment]
What browser was this in?

**Comment by ceylon23** [comment]
Latest Chrome.

**Comment by tjhrulz** [comment]
That should not be happening with the way I have it set up unless your version of the webpage is different than mine. Turn on debugging in Rainmeter and post what the actual error it is reporting is maybe that will give some insight into what is going on.

**Comment by ceylon23** [comment]
Here ya go. Sorry for the time delay. I am a US expat living in
Tajikistan. GMT+5
ERRO (10:43:57.696) : Web Side Error:Error updating repeat for
Amazon MusicDBUG (10:43:57.697) : Web Error:TypeError: Cannot read property
'getAttribute' of undefinedERRO (10:43:57.697) : Web Side Error:Error updating shuffle for
Amazon MusicDBUG (10:43:57.697) : Web Error:TypeError: Cannot read property
'getAttribute' of undefined



On Wed, Jan 24, 2018, at 11:13 AM, Trevor Hamilton wrote:
> That should not be happening with the way I have it set up unless your
> version of the webpage is different than mine. Turn on debugging in
> Rainmeter and post what the actual error it is reporting is.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/14#issuecomment-360206050

**Comment by tjhrulz** [comment]
There is no way that is the error if it is updated as I check that it is defined beforehand, your extension is still using the old code. Just use the new update I pushed to live last night.

**Comment by ceylon23** [comment]
I did. I removed the one I changed this morning and reinstalled the
0.4.1 version that you uploaded before enabling the debug. Still getting
this error. I will try on another computer.

On Thu, Jan 25, 2018, at 9:09 AM, Trevor Hamilton wrote:
> There is no way that is the error if it is updated as I literally do
> check that it is defined beforehand, you extension is still using the
> old code. Just use the new update I pushed it last night.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/14#issuecomment-360494242

**Comment by ceylon23** [comment]
It did work on another computer (a mac running rainmeter under wine). I therefore reinstalled chrome and all my extensions. It is working properly now. Thanks for you help in this. And thanks also for your time and efforts in creating these plugins. I've already built several skins for my own use and even modified SimpleSentence3 nowplaying skin.

**Comment by tjhrulz** [comment]
I'm glad it's working now my bet is that somehow the old plugin just wasn't getting disabled so the old code was still running
