### ISSUE TITLE
Soundcloud No Cover

### ISSUE THREAD

**Issue by Pein1911** [tjhrulz/WebNowPlaying-BrowserExtension#49]
It shows listening Soundcloud but not show cover

**Comment by osumunbro** [comment]
bump

**Comment by doZennn** [comment]
I think this is a problem with how [tjhrulz/WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying) is downloading covers, since the code to retrieve the cover art for SoundCloud still works fine.

**Comment by osumunbro** [comment]
> bump

bump

**Comment by Tearjuu** [comment]
Bumping. The plugin can't retrieve cover art from SoundCloud. There are errors appearing on the Rainmeter log. Other variables are working fine except for the cover art.

**Comment by tjhrulz** [comment]
fixed https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/6815d7bece82304b26d693336abc2064cb291eb6

**Comment by trevor-pope** [comment]
I still cannot retrieve the cover art. I updated the extension (version 0.4.8, last updated October 15, 2020). I am on Firefox 81.0.2

Not sure if Rainmeter is still trying to make an HTTPS request, since it logs an  HTTPS url.

Rainmeter logs the following:

Unable to get album art from: https://i1.sndcdn.com/artworks-000529495044-9l4ytz-t500x500.jpg

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)

**Comment by tjhrulz** [comment]
Hmmm, interesting. I am not at my computer today to look at this but maybe something different is going on with firefox. I'll look into this

**Comment by tjhrulz** [comment]
Lol I was a dummy, should be fixed now. I will probably try to deploy the most up to date version tonight or tomorrow to the firefox web store.

As for chrome, well I will deploy it as soon as they get around to reviewing my last version so I have to ability to upload a new version again.
