### ISSUE TITLE
Broken playback controls for YouTube

### ISSUE THREAD

**Issue by eileenthg** [tjhrulz/WebNowPlaying-BrowserExtension#64]
Ever since chrome implemented [this feature](https://support.google.com/chrome/answer/9692215?hl=en), the playback controls has broken for YouTube.
**Enabling "attempt general script everywhere" does not fix it.

* What still works:
    * Unpausing a video
    * Skip to next video

* What partially works:
    * Pausing video: YouTube seems to detect your attempt to pause the video, then immediately resumes playing.

* What doesn't work (or maybe input detected, but no effect shown):
    * Go back to previous video

### Versions
* Rainmeter Version: 4.3.1.3321
* OS Version: Windows 10 Pro 2004 64-bit (build 19041) - English (1033)
* Skin Version: 2.1.0
* Spotify Version: (Probably irrelevant, but) 2.1.5

* Chrome Version: 84.0.4147.125 (Official Build) (64-bit)

### Additional notes/images
The chrome feature appears when a media is playing. (Example, YouTube.)
![image](https://user-images.githubusercontent.com/40307498/90223800-4a5beb80-de41-11ea-9bba-63b31a233a77.png)

The issue was posted on Monstercat Visualizer, before they directed me to open an issue here.

**Comment by tjhrulz** [comment]
This issue has been fixed chrome just took their sweet time updating the extension, looks like they finally pushed my update out this morning. (Also how chrome gets that data is in a way only a browser can get and can not be used by an extension like this)

**Comment by eileenthg** [comment]
(I just tested, the pause function is still not working. What sort of witchery is chrome doing? The extension attempts to pause(and does pause) but chrome somehow immediately resumes playback. 0 A 0)
Everything else is working nicely though. Thanks for the work~

**Comment by tjhrulz** [comment]
Not sure what was going on there as I can not recreate the issue myself. Make sure there is not another extension installed that maybe is also interfacing with YouTube (Maybe try running in incognito mode with just the WebNowPlaying extension allowed to be used in incognito) and see if that fixes it.

Also make sure that the extension is updated to version 0.4.8
